baseURL : 'https://hzzhughes.github.io/'
languageCode : 'en-us'
title : '✌️Hanbin Zhou'
theme : 'PaperMod'

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
params:
  mainSections: []
  # homeInfoParams:
  #   Title: Welcome to Hughes's blog!
  #   Content: Hi there, I'm Hughes Zhou, this is my personal website, you can find more about me [here](about/).

  # socialIcons: # optional
  #   - name: "GitHub"
  #     url: "https://github.com/hzzhughes"
  #   - name: "RSS"
  #     url: "/index.xml"
  ShowCodeCopyButtons: true
  ShowToc: true
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

menu:
  main:
    - name: Blog
      url: post/
      weight: 1
    # - name: Misc
    #   url: misc/
    #   weight: 2
    # - name: Archive
    #   url: archives
    #   weight: 3
    # - name: Search
    #   url: search/
    #   weight: 3
    # - name: Tags
    #   url: tags/
    #   weight: 4
    # - name: Projects
    #   url: projects/
    #   weight: 2
# Add math compatibility
# extensions:
#   passthrough:
#     delimiters:
#       block:
#       - - \[
#         - \]
#       - - $$
#         - $$
#       inline:
#       - - \(
#         - \)
#       - - $
#         - $
#     enable: true